stages:
    - build
    - test
    - deploy

before_script:
    - 'printf "This is commit : $CI_COMMIT_SHORT_SHA\n"'

build:
    stage: build
    script:
        - echo "Build"
    when: always

test:
    stage: test
    script:
        - echo "Test"
    when: always

deploy-prd:
  stage: deploy
  environment:
    name: production
    url: https://der-prd-gitlab.fimmickapps.com
  script:
      - ssh ${ACCOUNT}@${IP} "cd ${PROJECT_PATH} && git checkout ${BRANCH} && git pull && exit"
  rules:
      - if: '$CI_COMMIT_BRANCH == "master"'
        when: manual
        allow_failure: false

deploy-staging:
  stage: deploy
  environment:
    name: staging
    url: https://der-uat-gitlab.fimmickapps.com
  script:
      - ssh ${ACCOUNT}@${IP} "cd ${PROJECT_PATH} && git checkout ${BRANCH} && git pull && exit"
  rules:
      - if: '$CI_COMMIT_BRANCH == "staging"'
        when: manual
        allow_failure: false
