stages:
    - test
    - deploy
    
before_script:
    - 'printf "This is commit : $CI_COMMIT_SHORT_SHA\n"'
    
echo-commit:
    stage: test
    script:
        - printf "This is Test...\nComplete test!!"
    
pull-latest:
    stage: deploy
    script:
        - ssh der-gitlab_uat@23.99.121.246 "cd /var/www/der-gitlab/der-uat-gitlab.fimmickapps.com/dermacept && git fetch --all && git pull --all && git checkout staging && exit"
    when: manual
    
pull-this:
    stage: deploy
    script:
        - ssh der-gitlab_uat@23.99.121.246 "cd /var/www/der-gitlab/der-uat-gitlab.fimmickapps.com/dermacept && git fetch --all && git pull --all && git checkout $CI_COMMIT_SHORT_SHA && exit"
    when: manual
    
# pull-commit:
#     stage: deploy
#     script:
#         - ssh der-gitlab_uat@23.99.121.246 "cd /var/www/der-gitlab/der-uat-gitlab.fimmickapps.com/dermacept && exit"
#     when: manual