stages:
    - build
    - test
    - deploy

before_script:
    - 'printf "This is commit : $CI_COMMIT_SHORT_SHA\n"'

build_staging:
    stage: build
    script:
        - echo "Build staging"
    rules:
        - if: '$CI_COMMIT_BRANCH == "staging"'
          when: always

build_prd:
    stage: build
    script:
        - echo "Build production"
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: always

test_staging:
    stage: test
    script:
        - echo "Test staging"
    rules:
        - if: '$CI_COMMIT_BRANCH == "staging"'
          when: always

test_prd:
    stage: test
    script:
        - echo "Test production"
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: always

deploy_staging:
    stage: deploy
    environment:
      name: staging
    script:
        - ssh ${ACCOUNT}@${IP} "cd ${PROJECT_PATH} && git checkout ${BRANCH} && git pull && exit"
    rules:
        - if: '$CI_COMMIT_BRANCH == "staging"'
          when: manual
          allow_failure: false

deploy_this_staging:
    stage: deploy
    environment:
      name: staging
    script:
        - ssh ${ACCOUNT}@${IP} "cd ${PROJECT_PATH} && git checkout ${BRANCH} && git pull && git checkout $CI_COMMIT_SHORT_SHA && exit"
    rules:
        - if: '$CI_COMMIT_BRANCH == "staging"'
          when: manual
          allow_failure: true

deploy_commit_staging:
    stage: deploy
    environment:
      name: staging
    script:
        - ssh ${ACCOUNT}@${IP} "cd ${PROJECT_PATH} && git checkout ${BRANCH} && git pull && git checkout $TARGET_COMMIT_SHORT_SHA && exit"
    rules:
        - if: '$CI_COMMIT_BRANCH == "staging"'
          when: manual
          allow_failure: true

deploy_prd:
    stage: deploy
    environment:
      name: production
    script:
        - ssh ${ACCOUNT}@${IP} "cd ${PROJECT_PATH} && git checkout ${BRANCH} && git pull && exit"
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: manual
          allow_failure: false

deploy_this_prd:
    stage: deploy
    environment:
      name: production
    script:
        - ssh ${ACCOUNT}@${IP} "cd ${PROJECT_PATH} && git checkout ${BRANCH} && git pull && git checkout $CI_COMMIT_SHORT_SHA && exit"
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: manual
          allow_failure: true

deploy_commit_prd:
    stage: deploy
    environment:
      name: staging
    script:
        - ssh ${ACCOUNT}@${IP} "cd ${PROJECT_PATH} && git checkout ${BRANCH} && git pull && git checkout $TARGET_COMMIT_SHORT_SHA && exit"
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: manual
          allow_failure: true
