stages:
    - build
    - test
    - deploy

before_script:
    - 'printf "This is commit : $CI_COMMIT_SHORT_SHA\n"'

build_staging:
    stage: build
    script:
        - echo "Build staging"
    rules:
        - if: '$CI_COMMIT_BRANCH == "staging"'
          when: manual
          allow_failure: false

build_prd:
    stage: build
    script:
        - echo "Build production"
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: manual
          allow_failure: false

test_staging:
    stage: test
    needs: ['build_staging']
    script:
        - echo "Test staging"

test_prd:
    stage: test
    needs: ['build_prd']
    script:
        - echo "Test production"

deploy_staging:
    stage: deploy
    needs: ['test_staging']
    environment:
      name: staging
      url: https://der-uat-gitlab.fimmickapps.com
    script:
        - ssh ${ACCOUNT}@${IP} "cd ${PROJECT_PATH} && git checkout ${BRANCH} && git pull && exit"

deploy_prd:
    stage: deploy
    needs: ['test_prd']
    environment:
      name: production
      url: https://der-prd-gitlab.fimmickapps.com
    script:
        - ssh ${ACCOUNT}@${IP} "cd ${PROJECT_PATH} && git checkout ${BRANCH} && git pull && exit"
