stages:
    - test
    - deploy
    
before_script:
    - 'printf "This is commit : $CI_COMMIT_SHORT_SHA\n"'
    
echo-commit:
    stage: test
    script:
        - printf "This is Test...\nComplete test!!"
    
echo-variable:
    stage: test
    script:
        - printf "This is Test 2 with variable $$str=$str...\nComplete test!!"
    when: manual
    
pull-latest:
    stage: deploy
    script:
        - ssh der-gitlab_uat@23.99.121.246 "cd /var/www/der-gitlab/der-uat-gitlab.fimmickapps.com/dermacept && git checkout master && git pull --all && exit"
    when: manual
    
pull-this:
    stage: deploy
    script:
        - ssh der-gitlab_uat@23.99.121.246 "cd /var/www/der-gitlab/der-uat-gitlab.fimmickapps.com/dermacept && git checkout master && git pull --all && git checkout $CI_COMMIT_SHORT_SHA && exit"
    when: manual
    
pull-commit:
    stage: deploy
    script:
        - ssh der-gitlab_uat@23.99.121.246 "cd /var/www/der-gitlab/der-uat-gitlab.fimmickapps.com/dermacept && git checkout master && git pull --all && git checkout $TARGET_COMMIT_SHORT_SHA && exit"
    when: manual
