stages:
    - build
    - test
    - deploy
    
before_script :
    - 'printf "This is commit : $CI_COMMIT_SHORT_SHA\n"'

uat-build:
    stage: build
    rules:
        - if: $CI_COMMIT_BRANCH == "staging"
          when: always
    variables:
        ACCOUNT: der-gitlab_uat
        IP: 23.99.121.246
        PATH: /var/www/der-gitlab/der-uat-gitlab.fimmickapps.com/dermacept/staging
        BRANCH: staging
    script:
        - printf "This is Staging !!!"
      
prd-build:
    stage: build
    rules:
        - if: $CI_COMMIT_BRANCH == "master"
          when: always
    variables:
        ACCOUNT: der-gitlab_uat
        IP: 23.99.121.246
        PATH: /var/www/der-gitlab/der-uat-gitlab.fimmickapps.com/dermacept
        BRANCH: master
    script:
        - printf "This is Production !!!"
        
echo-commit:
    stage: test
    script:
        - printf "This is Test...\nComplete test!!"
    
pull-latest:
    stage: deploy
    script:
        - ssh ${ACCOUNT}@${IP} "cd ${PATH} && git checkout ${BRANCH} && git pull && exit"
    when: manual
    
pull-this:
    stage: deploy
    script:
        - ssh ${ACCOUNT}@${IP} "cd ${PATH} && git checkout ${BRANCH} && git pull && git checkout $CI_COMMIT_SHORT_SHA && exit"
    when: manual
    
pull-commit:
    stage: deploy
    script:
        - ssh ${ACCOUNT}@${IP} "cd ${PATH} && git checkout ${BRANCH} && git pull && git checkout $TARGET_COMMIT_SHORT_SHA && exit"
    when: manual

pull-tag:
    stage: deploy
    script:
        - ssh ${ACCOUNT}@${IP} "cd ${PATH} && git checkout ${BRANCH} && git pull && git checkout tags/$TARGET_TAG_NAME && exit"
    when: manual


